services:
  legion:
    container_name: legion
    build:
      context: .
    command: /usr/bin/legion
    restart: always
    ports:
      - 50051:50051
    depends_on:
      - postgres
      - redis

  legion-runner:
    container_name: legion-runner
    build:
      context: .
    command: /usr/bin/legion-runner
    restart: always
    ports:
      - 50052:50052
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=legion
    volumes:
      - .docker-volumes/postgres/:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    container_name: redis
    image: redis:7.4
    restart: always
    volumes:
      - .docker-volumes/volumes/redis:/data
    ports:
      - 6379:6379

  minio:
    container_name: minio
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    environment:
      MINIO_ROOT_USER: minio_user
      MINIO_ROOT_PASSWORD: minio_password
    command: server --address ":9001" --console-address ":9002" /data
    volumes:
      - .docker-volumes/minio/data:/data
    ports:
      - 9001:9001
      - 9002:9002
