# Конфигурация основного сервера Legion

server:
  host: "0.0.0.0"
  port: "50051"

postgres:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "postgres"
  database: "legion"

redis:
  host: "127.0.0.1"
  port: 6379
  auth:
  database: 0

minio:
  host: "127.0.0.1"
  port: 9001
  ssl: false
  secret_id: "minio_user"
  secret_key: "minio_password"
  bucket: "legion"

jwt:
  access_secret: "legion"
  refresh_secret: "legion"
  access_ttl: 15m
  refresh_ttl: 168h

runners:
  registration_token: ""
  addresses:
    - "127.0.0.1:50052"

log:
  # debug, verbose, info, warn, error, off
  level: "debug"
